# Generated by Django 4.1.7 on 2023-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_stat',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'InActive'), ('L', 'Latest'), ('T', 'Trending'), ('H', 'Hot'), ('S', 'Sale'), ('F', 'Featured'), ('N', 'New'), ('O', 'Top Seller')], max_length=1, null=True),
        ),
    ]
