# Generated by Django 4.1.7 on 2023-04-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_prod_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_stat',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'InActive'), ('L', 'Latest'), ('T', 'Trending'), ('H', 'Hot'), ('S', 'Sale'), ('F', 'Featured'), ('N', 'New'), ('O', 'Top Seller'), ('R', 'Top Rated')], max_length=1, null=True),
        ),
    ]
